version: "3.5"
services:
  nats:
    image: nats
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    command: "--auth test-token"
    networks:
      - nats
networks:
  nats:
    name: nats