version: "3.9"
services:
  flyway:
    image: flyway/flyway:latest
    command: >
      -user="${DB_USER}"
      -password="${DB_PASSWORD}"
      -url=jdbc:postgresql://db:${DB_PORT}/${DB_NAME}
      migrate
    volumes:
      - ./flyway/sql:/flyway/sql
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - ${DB_PORT}:5432
    container_name: db
