[package]
name = "parallel_tasks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.1"
rand = "0.8.4"
glob = "0.3.0"
image = "0.23.14"
error-chain = "0.12.4"