[package]
name = "csv_processing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12.4"
csv = "1.1.6"
serde = { version = "1.0.132", features = ["derive"] }
